# Generated by Django 3.1.5 on 2021-01-20 14:29

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_class', models.IntegerField()),
                ('student_subject', multiselectfield.db.fields.MultiSelectField(choices=[('CS', 'Computer Science'), ('CE', 'Civil'), ('ME', 'Mechanical')], max_length=20)),
                ('student_marks', models.IntegerField()),
            ],
        ),
    ]
