# Generated by Django 3.1.5 on 2021-02-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='inde',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
