# Generated by Django 3.1.5 on 2021-02-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0002_auto_20210203_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='totalbal',
            field=models.IntegerField(default=0),
        ),
    ]
