# Generated by Django 3.1.5 on 2021-01-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('classes', models.IntegerField()),
                ('division', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
